flaskblog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms.validators import DataRequired
from wtforms import StringField, SubmitField, TextAreaField


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

flaskblog/main/routes.py
from flask import Blueprint, render_template, request
from flaskblog.models import Post

main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home")
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page,
                                                                  per_page=5)
    return render_template('home.html', posts=posts)


@main.route("/about")
def about():
    return render_template('about.html', title="About")

flaskblog/posts/routes.py
from flask import (render_template, request, url_for, flash, redirect, abort,
                   Blueprint)
from flask_login import current_user, login_required
from flaskblog import db
from flaskblog.models import Post
from flaskblog.posts.forms import PostForm

posts = Blueprint('posts', __name__)


@posts.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data,
                    author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Post', form=form)


@posts.route('/post/<int:post_id>')
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!')
        return redirect(url_for('posts.post', post_id=post_id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    form.title.data = post.title
    form.content.data = post.content
    return render_template('create_post.html', title='Update Post', form=form)


@posts.route('/post/<int:post_id>/delete', methods=['GET', 'POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!')
    return redirect(url_for('main.home'))

flaskblog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flaskblog import db, bcrypt
from flaskblog.models import User, Post
from flaskblog.users.forms import (RegistrationForm, LoginForm,
                                   UpdateAccountForm, RequestResetForm,
                                   ResetPasswordForm)
from flaskblog.users.utils import save_picture, send_reset_email
import os
from flask import current_app

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data) \
            .decode('utf-8')
        user = User(username=form.username.data,
                    email=form.email.data,
                    password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in')
        return redirect(url_for('main.home'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            flash(f'Hello, {user.username}!')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login unsuccessful. Please check email and password')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    flash('You have been logged out!')
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            old_image = os.path.join(current_app.root_path, 'static', 'profile',
                                     current_user.image_file)
            os.remove(old_image)
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static',
                         filename=f'profile/{current_user.image_file}')
    return render_template('account.html',
                           title='Account',
                           image_file=image_file,
                           form=form)


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user) \
        .order_by(Post.date_posted.desc()) \
        .paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    print(token)
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        print("USER IS NONE")
        flash('That is an invalid or expired token')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data) \
            .decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset password', form=form)

flaskblog/templates/about.html
{% extends "layout.html" %}


{% block content %}
<h1>About page</h1>
{% endblock content%}

flaskblog/templates/account.html
{% extends "layout.html" %}


{% block content %}

<div class="card-panel grey lighten-5 z-depth-1">
    <div class="row valign-wrapper">
        <div class="col s3">
            <img src="{{ image_file }}" alt="" class="circle responsive-img"> <!-- notice the "circle" class -->
        </div>
        <div class="col s10">
            <h2>{{ current_user.username }}</h2>
            <p>{{ current_user.email }}</p>
        </div>
    </div>
    <div class="row valign-wrapper">
        <form class="col s12" method="POST" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <div class="input-field col s12">
                {{ form.username() }}
                {% if form.username.errors %}
                <div>
                    {% for error in form.username.errors %}
                    <span class="helper-text red-text">{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
                {{ form.username.label() }}
            </div>
            <div class="input-field col s12">
                {{ form.email() }}
                {% if form.email.errors %}
                <div>
                    {% for error in form.email.errors %}
                    <span class="helper-text red-text">{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
                {{ form.email.label() }}
            </div>
            <div class="input-field col s12">
                <div class="file-field input-field">
                    <div class="btn">
                        <span>File</span>
                        <input type="file">
                    </div>
                    <div class="file-path-wrapper">
                        {{ form.picture() }}
                        <input class="file-path validate" type="text">
                        {% if form.picture.errors %}
                        <div>
                            {% for error in form.picture.errors %}
                            <span class="helper-text red-text">{{ error }}</span>
                            {% endfor %}
                        </div>
                        {% endif %}
                        {{ form.picture.label() }}
                    </div>
                </div>
            </div>
            <div>
                {{ form.submit(class="btn") }}
            </div>
        </form>
    </div>
</div>

{% endblock content%}

flaskblog/templates/create_post.html
{% extends "layout.html" %}

{% block content %}
<div>
    <form class="col s12" method="POST">
        {{ form.hidden_tag() }}
        <div class="input-field col s12">
            {{ form.title() }}
            {% if form.title.errors %}
            <div>
                {% for error in form.title.errors %}
                <span class="helper-text red-text">{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
            {{ form.title.label() }}
        </div>
        <div class="input-field col s12">
            {{ form.content() }}
            {% if form.content.errors %}
            <div>
                {% for error in form.content.errors %}
                <span class="helper-text red-text">{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
            {{ form.content.label() }}
        </div>
        <div class="row">
            <div class="col s6">
                {{ form.submit(class="btn") }}
            </div>
        </div>
    </form>
</div>
{% endblock content%}

flaskblog/templates/home.html
{% extends "layout.html" %}

{% block content %}
{% for post in posts.items %}
    <div class="section">
        <div class="col s4 m2">
            <img src="{{ url_for('static', filename='profile/'+ post.author.image_file) }}" alt=""
                 class="circle responsive-img"> <!-- notice the "circle" class -->
        </div>
        <h5><a href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h5>
        <p>By <a href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>,
            <small class="grey-text text-darken-2">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
        </p>
        <p style="text-align: justify">{{ post.content }}</p>

    </div>
    <div class="divider"></div>
{% endfor %}
<ul class="pagination">
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if posts.page == page_num %}
                <li class="active teal lighten-2"><a href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a></li>
            {% else %}
                <li><a href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a></li>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
</ul>
{% endblock content%}

flaskblog/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="shortcut icon" href="{{ url_for('static', filename='flask_favicon.ico') }}">
    {% if title %}
    <title>Flask Blog - {{title}}</title>
    {%else%}
    <title>Flask Blog</title>
    {%endif%}
    <script>
        document.addEventListener('DOMContentLoaded', function() {
        var elem = document.querySelector('.sidenav');
        var instance = new M.Sidenav(elem);
        });







    </script>
</head>

<body>
<header>
    <nav>
        <div class="nav-wrapper blue-grey darken-1">
            <div class="container">
                <div class="container">
                    <a href="{{ url_for('main.home') }}" class="brand-logo">Flask blog</a>
                    <a href="{{ url_for('main.home') }}" data-target="mobile-demo" class="sidenav-trigger"><i
                            class="material-icons">menu</i></a>
                    <ul class="right hide-on-med-and-down">
                        <li><a href="{{ url_for('main.home') }}">Home</a></li>
                        <li><a href="{{ url_for('main.about') }}">About</a></li>
                        {% if current_user.is_authenticated %}
                        <li><a href="{{ url_for('posts.new_post') }}">New Post</a></li>
                        <li><a href="{{ url_for('users.account') }}">Account</a></li>
                        <li><a href="{{ url_for('users.logout') }}">Logout</a></li>
                        {% else %}
                        <li><a href="{{ url_for('users.login') }}">Login</a></li>
                        <li><a href="{{ url_for('users.register') }}">Register</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
    </nav>
    <ul class="sidenav" id="mobile-demo">
        {% if current_user.is_authenticated %}
        <li>
            <div class="user-view">
                <div class="background">
                    <img src="{{ url_for('static', filename='office.jpg') }}">
                </div>
                <img class="circle" src="{{ url_for('static', filename='profile/'+ current_user.image_file) }}">
                <span class="white-text name">{{current_user.username}}</span>
                <span class="white-text email">{{current_user.email}}</span>
            </div>
        </li>
        <li><a class="waves-effect" href="{{ url_for('posts.new_post') }}">New Post</a></li>
        <li><a class="waves-effect" href="{{ url_for('users.account') }}">Account</a></li>
        <li><a class="waves-effect" href="{{ url_for('users.logout') }}">Logout</a></li>
        {% else %}
        <li><a class="waves-effect" href="{{ url_for('users.login') }}">Login</a></li>
        <li><a class="waves-effect" href="{{ url_for('users.register') }}">Register</a></li>
        {% endif %}
        <li>
            <div class="divider"></div>
        </li>
        <li><a class="waves-effect" href="{{ url_for('main.home') }}">Home</a></li>
        <li><a class="waves-effect" href="{{ url_for('main.about') }}">About</a></li>
    </ul>

</header>

<body>
<div class="container">
    <main role="main" class="container">
        <div class="row">
            <div class="col m8 s12">
                {% with messages =get_flashed_messages(with_categories=true) %}
                {% if messages %}
                {% for category, message in messages %}
                <div class="card-panel green accent-1">
                    {{ message }}
                </div>
                {% endfor %}
                {% endif %}
                {% endwith %}
                {% block content %}{% endblock %}
            </div>
            <div class="col l4 m4 s12">
                <div class="card blue-grey darken-1">
                    <div class="card-content white-text">
                        <span class="card-title">Our sidebar</span>
                        <p>You can put any information here you'd like.</p>
                    </div>
                    <div class="card-action">
                        <ul>
                            <li><a href="#">Latest Posts</a></li>
                            <li><a href="#">News</a></li>
                            <li><a href="#">Calendars</a></li>
                            <li><a href="#">etc</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </main>
</div>

flaskblog/templates/login.html
{% extends "layout.html" %}


{% block content %}
<div>
    <form class="col s12" method="POST">
        {{ form.hidden_tag() }}
        <div class="input-field col s12">
            {{ form.email() }}
            {% if form.email.errors %}
            <div>
                {% for error in form.email.errors %}
                <span class="helper-text red-text">{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
            {{ form.email.label() }}
        </div>
        <div class="input-field col s12">
            {{ form.password() }}
            {% if form.password.errors %}
            <div>
                {% for error in form.password.errors %}
                <span class="helper-text red-text">{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
            {{ form.password.label() }}
        </div>
        <div class="row">
            <div class="col s6">
                {{ form.submit(class="btn") }}
            </div>
            <div class="col s6">
                <label>
                    {{ form.remember() }}
                    <span> {{ form.remember.label() }}</span>
                </label>
            </div>
        </div>
        <div>
            <small>
                <a href="{{ url_for('users.reset_request') }}">Forgot password?</a>
            </small>
        </div>
    </form>
</div>

{% endblock content%}

flaskblog/templates/post.html
{% extends "layout.html" %}

{% block content %}
<div class="section">
    <div class="col s4 m2">
        <img src="{{ url_for('static', filename='profile/'+ post.author.image_file) }}" alt=""
             class="circle responsive-img"> <!-- notice the "circle" class -->
    </div>
    <h5>{{ post.title }}</h5>
    <p>By <a href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>,
        <small class="grey-text text-darken-2">{{ post.date_posted.strftime('%Y-%m-%d') }}</small></p>
    {% if post.author == current_user %}
    <div>
        <a class="btn waves-effect waves-teal" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
        <!-- Modal Trigger -->
        <a class="waves-effect waves-light red lighten-2 btn modal-trigger" href="#modal1">Delete</a>
        <!-- Modal Structure -->
        <div id="modal1" class="modal">
            <div class="modal-content">
                <h4>Delete post</h4>
                <p>This action cannot be undone!</p>
            </div>
            <div class="modal-footer">
                <a href="javascript:void(0);"
                   class="modal-close waves-effect waves-light yellow lighten-2 btn-flat">Cancel</a>
                <a href="{{ url_for('posts.delete_post', post_id=post.id) }}"
                   class="modal-close waves-effect waves-light red lighten-2 btn-flat">Delete</a>
            </div>
        </div>
    </div>

    {% endif %}

    <p style="text-align: justify">{{ post.content }}</p>
</div>

<div class="divider"></div>
<script>
document.addEventListener('DOMContentLoaded', function() {
  var elems = document.querySelectorAll('.modal');
  var instances = M.Modal.init(elems);
});







</script>
{% endblock content%}

flaskblog/templates/register.html
{% extends "layout.html" %}


{% block content %}
<div>
    <form class="col s12" method="POST">
        {{ form.hidden_tag() }}
        <div class="input-field col s12">
            {{ form.username() }}
            {% if form.username.errors %}
            <div>
                {% for error in form.username.errors %}
                <span class="helper-text red-text">{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
            {{ form.username.label() }}
        </div>
        <div class="input-field col s12">
            {{ form.email() }}
            {% if form.email.errors %}
            <div>
                {% for error in form.email.errors %}
                <span class="helper-text red-text">{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
            {{ form.email.label() }}
        </div>
        <div class="input-field col s12">
            {{ form.password() }}
            {% if form.password.errors %}
            <div>
                {% for error in form.password.errors %}
                <span class="helper-text red-text">{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
            {{ form.password.label() }}
        </div>
        <div class="input-field col s12">
            {{ form.confirm_password() }}
            {% if form.confirm_password.errors %}
            <div>
                {% for error in form.confirm_password.errors %}
                <span class="helper-text red-text">{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
            {{ form.confirm_password.label() }}
        </div>
        <div>
            {{ form.submit(class="btn") }}
        </div>
    </form>
    <div>
        <small>
            Already have an account? <a href="{{ url_for('users.login') }}">Sign in</a>
        </small>
    </div>
</div>

{% endblock content%}

flaskblog/templates/reset_request.html
{% extends "layout.html" %}


{% block content %}
<div>
    <form class="col s12" method="POST">
        {{ form.hidden_tag() }}
        <div class="input-field col s12">
            {{ form.email() }}
            {% if form.email.errors %}
            <div>
                {% for error in form.email.errors %}
                <span class="helper-text red-text">{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
            {{ form.email.label() }}
        </div>
        <div class="row">
            <div class="col s6">
                {{ form.submit(class="btn") }}
            </div>
        </div>
    </form>
</div>

{% endblock content%}

flaskblog/templates/reset_token.html
{% extends "layout.html" %}


{% block content %}
<div>
    <form class="col s12" method="POST">
        {{ form.hidden_tag() }}
        <div class="input-field col s12">
            {{ form.password() }}
            {% if form.password.errors %}
            <div>
                {% for error in form.password.errors %}
                <span class="helper-text red-text">{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
            {{ form.password.label() }}
        </div>
        <div class="input-field col s12">
            {{ form.confirm_password() }}
            {% if form.confirm_password.errors %}
            <div>
                {% for error in form.confirm_password.errors %}
                <span class="helper-text red-text">{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
            {{ form.confirm_password.label() }}
        </div>
        <div class="row">
            <div class="col s6">
                {{ form.submit(class="btn") }}
            </div>
        </div>
    </form>
</div>

{% endblock content%}

flaskblog/templates/user_posts.html
{% extends "layout.html" %}

{% block content %}
<h3>Posts by {{ user.username }} ({{ posts.total }})</h3>
{% for post in posts.items %}
    <div class="section">
        <div class="col s4 m2">
            <img src="{{ url_for('static', filename='profile/'+ post.author.image_file) }}" alt=""
                 class="circle responsive-img"> <!-- notice the "circle" class -->
        </div>
        <h5><a href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h5>
        <p>By <a href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>,
            <small class="grey-text text-darken-2">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
        </p>
        <p style="text-align: justify">{{ post.content }}</p>

    </div>
    <div class="divider"></div>
{% endfor %}
<ul class="pagination">
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if posts.page == page_num %}
                <li class="active teal lighten-2"><a href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a></li>
            {% else %}
                <li><a href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a></li>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
</ul>
{% endblock content%}